### ISSUE TITLE
Wrong example in Cirrus Form Inputs documentation

### ISSUE THREAD

**Issue by Randerspl** [Spiderpig86/Cirrus#71] opened 2021-08-18 14:07 UTC
**Describe the bug**
I think i found a small bug in documentation.  
In _Form Inputs_ example element inside div is created as _p_ but closes as _span_  
![image](https://user-images.githubusercontent.com/9450923/129912995-fd648ca6-aed6-4e80-ad60-9d85502d9071.png)

**To Reproduce**
Enter page [Form Inputs](https://cirrus-ui.netlify.app/forms/inputs) and look on example.

**Comment by Randerspl** [comment] 2021-08-24 09:37
This error exists in more than one line in example Look on next input group example. Commit fixes only one occurrence.

**Comment by Spiderpig86** [comment] 2021-08-24 17:34
Thanks for the report! It should be fixed. I discovered that Netlify auto-publishing stopped working as well, so the docs are being republished. Last update was 2021-07-14.

**Comment by Randerspl** [comment] 2021-08-25 11:38
Great work. Now i see that values are ok in example. 

But i think i found something else.
In Input Forms example i don't see horizontal bar and i need to select text to scroll.
![image](https://user-images.githubusercontent.com/9450923/130784031-29a50d94-b40f-4761-97b1-dd77c422eb92.png)

In #Sizes scrollbar appears and its ok.
![image](https://user-images.githubusercontent.com/9450923/130784107-02cc732a-da3b-46eb-b4e2-8208b8f972fb.png)

**Comment by Randerspl** [comment] 2021-08-25 11:40
Ok i found something. 
I need first to scroll to bottom of element to see horizontal scrollbar
![image](https://user-images.githubusercontent.com/9450923/130784373-4c064bc2-b65e-403d-bb60-f2ff07bd70ae.png)

**Comment by Spiderpig86** [comment] 2021-08-25 16:21
Yup, that's as intended. Thanks for reporting the issue, feel free to open a new one if anything else arises. Resolving.

**Closed by Spiderpig86** 2021-08-25 16:21 UTC
